### ISSUE TITLE
CI test for extensions (is now: remove extensions feature)

### ISSUE THREAD

**Issue by adnelson** [adnelson/nixfromnpm#120]
Test the `-e` option

**Comment by ixmatus** [comment]
I think if we want to release a `1.0.0` soon we should get in #117 which would be a backwards breaking change _and_ remove the extensions feature (thereby removing the need to exercise it with CI).

What do you think about doing that? I have some free-time I can commit to that work.

**Comment by adnelson** [comment]
I guess I'm OK with removing extensions. I'm not sure anyone uses it, and it's currently broken anyway. It is a useful thing though, distinct from what's laid out in #117 because `nixfromnpm` has logic to discover packages in the initial package set so that they don't need to be duplicated in the extension set. It also enables one to reuse to a package definition which might have been fixed by hand.

But, arguably all of this can be accomplished by just cloning `nix-node-packages` instead of building from scratch. So, yeah I think we can get rid of it.

**Comment by adnelson** [comment]
Fixed in #126
