### ISSUE TITLE
fsevents on darwin fails to build the gyp bindings

### ISSUE THREAD

**Issue by ixmatus** [adnelson/nixfromnpm#122]
This _might be_ related to the work in #115; we saw gyp binding failures but were not concerned about it and weren't convinced the failures were caused by #115. This ticket tracks the issue with a specific and concrete package so we can fix it if it becomes a blocking issue for any users.

**Comment by adnelson** [comment]
Curious if this works on linux.

**Comment by adnelson** [comment]
I just noticed something, the build of `1.1.3` (and other versions I've seen) fails with:

```
gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp
```

Looking at the package.json, I'm seeing this section:

```
  "binary": {
    "module_name": "fse",
    "module_path": "./lib/binding/{configuration}/{node_abi}-{platform}-{arch}/",
    "remote_path": "./v{version}/",
    "package_name": "{module_name}-v{version}-{node_abi}-{platform}-{arch}.tar.gz",
    "host": "https://fsevents-binaries.s3-us-west-2.amazonaws.com"
  },
```

It's probably not a coincidence that `module_name` appears here. Maybe there's some information we're supposed to be passing to `gyp`?

Still weird that it worked on linux though.
