### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by dksim** [adnelson/nixfromnpm#137]
I get the following error when trying to install (using NixOS 18.03)

> error: store path mismatch in file downloaded from 'https://github.com/NixOS/nixpkgs/archive/3389f23412877913b9d22a58dfb241684653d7e9.tar.gz'

**Comment by adnelson** [comment]
@dksim Sorry to be slow to respond -- can you be a little clearer which command(s) you're running that cause this error?

**Comment by dksim** [comment]
The following command causes the error
`nix-env --install --attr nixfromnpm --file ./release.nix`

**Comment by ixmatus** [comment]
@adnelson #133 fixes @dksim's issue.

**Comment by ixmatus** [comment]
Fixed by #133.
