### ISSUE TITLE
"Error in $: expected string, encountered Object" when trying to parse deep-diff package

### ISSUE THREAD

**Issue by srghma** [adnelson/nixfromnpm#138]
full output https://pastebin.com/FFNgt1Fm
output that is highlighted with red https://pastebin.com/9LtWhyQC

commit with this issue https://github.com/srghma/my-create-react-app/tree/17ffe59d472c2d7b9647c36c57b38a45023e67f7

nixfromnpm is installed with https://github.com/srghma/dotfiles/blob/c4e30e02e59bf087b7129573c1cf63af479883f6/nixos/pkgs/nixfromnpm/default.nix#L4

how to reproduce:

`nixfromnpm -f package.json -o nix`

**Comment by srghma** [comment]
@adnelson hi, can you please suggest what should be fixed here, maybe I could even help)

**Comment by ixmatus** [comment]
@srghma it sounds like the `deep-diff` package's `package.json` does not conform to valid JSON:

```
WARNING: Failed to fetch dependency deep-diff version >=0.3.5 <0.4.0: InvalidPackageJson
```

... have you tried extracting the `package.json` from the exact version `nixfromnpm` resolves and hand-inspecting it?

I have encountered at least two packages with this type of issue and I had to override the package and apply a patch to the `package.json`.

**Comment by ixmatus** [comment]
e.g. I've had to do something like this:

```
let

  generatedNodePackages = import ./nodePackages {
    nodejs = nodejs-6_x;

    inherit pkgs;
  };

  npm = generatedNodePackages.override {

    overrides = nodePackagesNew: nodePackagesOld: rec {
      # `mold-source-map` specifies a "main" field in it's
      # `package.json` which points to non-existent file. This causes
      # `nixfromnpm` to fail with an error message of "Main entry
      # point index does not exist".
      mold-source-map       = mold-source-map_0-4-0;
      mold-source-map_0-4-0 = nodePackagesOld.mold-source-map_0-4-0.overrideNodePackage (oldAttrs: {
        derivationOverrides = {
          patchPhase = (oldAttrs.patchPhase or "") + ''
            ${patch}/bin/patch < ${./remove-main-00.patch}
          '';
        };
      });
    };

  };

in

  ...
```

**Comment by srghma** [comment]
@ixmatus tnx, just wanted to ask for example ) I'll look at weekends)

**Comment by adnelson** [comment]
So I think there are a few issues here:

1. If `npm` is able to parse the JSON, then we probably should too, unless this is a truly pathological case. I don't know if this means using a more permissive parser than Aeson, but there are other options.
2. In this kind of situation we should definitely not be returning a successful exit code. It's been a long-standing gripe of mine. Admittedly there's a tension between "stop as soon as an error is encountered" and "go as far as possible, just note when there are errors". But regardless, a state like this should at least not return `0`.

In any case I'm looking into this, not sure how much time I'll have on it though.

**Comment by srghma** [comment]
@adnelson hi, so you will look why this is happening, tnx

what about issue that @ixmatus described, why nixfromnpm should check whether `main` field of package.json link to existing file?

**Comment by adnelson** [comment]
I don't *think* (although I'm not sure) that that is the same issue as what we're seeing here. What looks like is happening right now, is that it's trying to parse the JSON that the NPM server is giving as a response to "give me all of the versions of `deep-diff` that you have", and the parser can't understand the JSON structure that's being sent. So, it can't generate a definition of the package at all.

**Comment by srghma** [comment]
@adnelson tnx for the fix !!

re `dont check that main field of package.json links to existing file`:
1. sorry for asking this here, I should have created the different issue
1. I thought it would be tedious to write patch each time nixfromnpm encounters the issue like this just to appease nixfromnpm (because npm doesnt chech things like this), but I think nixfromnpm does right job: `main` is one of the most important fields and `mold-source-map` package in example above made a mistake that should be fixed either by making patch or clone

**Comment by ixmatus** [comment]
@srghma looks like I created confusion with my comments. I was trying to provide an example of a `package.json` that was misbehaving for me and how I overrode it, I did not think it was specifically related to your issue. Further proven by @adnelson's PR #139.

@srghma `main` only matters when you need to have an entrypoint, for libraries it doesn't really matter and in the `mold-source-map` case it did not. However, I agree with your point that we should contribute fixes upstream when we encounter cases like these and in this particular case I chose not to because the project looks dead and I also didn't have time.
