### ISSUE TITLE
BROKEN packages aren't very user friendly

### ISSUE THREAD

**Issue by teh** [adnelson/nixfromnpm#52]
They throw the error:

```
error: attribute ‘uniqueName’ missing, at /tmp/testnpmfromnix/nodeLib/buildNodePackage.nix:187:54
```

for packages like  `BROKEN-readable-stream` - not sure what to best fix but it took me a while to figure out.

**Comment by adnelson** [comment]
Yeah the broken packages kinda blow. I'm going to try to come up with a better approach to this.
