### ISSUE TITLE
dependencies with git+ssh url

### ISSUE THREAD

**Issue by gilligan** [adnelson/nixfromnpm#59]
In my project I have several entries like the following:
```
"foobar: "git+ssh://git@local.github/some/package.git#1.2.3"
```

So for this I would have to use ssh keys. nix provides `fetchgitPrivate` for this usecase. How could this work with nixfromnpm ?

**Comment by adnelson** [comment]
So github URLs, especially private ones, are something I've done a bit of work on but are not super robust yet. What you can do is create an access token on github, and set this as the `GITHUB_TOKEN` environment variable. I don't think that I have the capability of resolving `git+ssh` urls, but if you change it to a `https://github.com` it will hopefully work.
