### ISSUE TITLE
Resolving github URLs

### ISSUE THREAD

**Issue by gilligan** [adnelson/nixfromnpm#74]
Both of the following are valid URL specifiers for npm but only the latter can be parsed by nixfromnpm:

```
"holidaycheck/react-autosuggest#43074a439d26243ea07110f0c5752a6fc8aebe4d"
```

```
"react-autosuggest": "https://github.com/holidaycheck/reactautosuggest#43074a439d26243ea07110f0c5752a6fc8aebe4d"
```

**Comment by adnelson** [comment]
Thanks for letting me know; this should be fixed now. Git fetching is still a bit of a hairy ugly beast but fixing this did give me the opportunity to improve the situation a little.
