### ISSUE TITLE
Generated nodeLib does not include necessary tools directory

### ISSUE THREAD

**Issue by ixmatus** [adnelson/nixfromnpm#78]
I'm trying to use `nixfromnpm` (the latest git revision) but I'm running into a problem: the `tools` directory found inside the `nodeLib` of this repository is not being included in the generated `nodeLib` dir.

**Comment by adnelson** [comment]
Ah, I think the bug is here: https://github.com/adnelson/nixfromnpm/blob/master/src/NixFromNpm/Conversion/ToDisk.hs#L184

I'll try to take a stab at this today or tomorrow.

**Comment by ixmatus** [comment]
Yes, that is what I concluded too. I will have a PR up shortly with a proposal for a fix.

**Comment by adnelson** [comment]
That would be great!
