### ISSUE TITLE
Test and executable sections in nixfromnpm.cabal do not depend on the nixfromnpm library

### ISSUE THREAD

**Issue by ixmatus** [adnelson/nixfromnpm#80]
This isn't _bad_ but it is inefficient because source files are compiled for the library section, the executable section, and the test section.

If the executable section and the test section both referenced `nixfromnpm` in their `build-depends` then they wouldn't need to build `src`. This also means many of the `build-depends` deps can be dropped from those two sections as well.

**Comment by adnelson** [comment]
I think I set it up that way so that when I'm iterating on tests, I could hit `:r` in the repl and it would reload the library code as well as the test code. There's probably a better way to do accomplish this.
