### ISSUE TITLE
skipOptionalDependencies doesn't appear to do anything?

### ISSUE THREAD

**Issue by ixmatus** [adnelson/nixfromnpm#81]
Building `chokidar` on Linux fails because `fsevents` is Darwin only. Adding `fsevents` to the `skipOptionalDependencies` doesn't change the behavior at all. Furthermore the code doesn't do anything with that binding except remove it from the final attribute set.

Am I misunderstanding how `skipOptionalDependencies` is intended to be used?

**Comment by adnelson** [comment]
Looking at the nix definition, this option doesn't do anything. It probably did at one point. I can take a look at it.

**Comment by ixmatus** [comment]
I should add that when I build with `node-4_x` it seems to skip without being told to. If I build with `node-6_x` it throws a hissy fit.

**Comment by ixmatus** [comment]
Also, I'm very happy to help tweak this if there's more context about how it was intended or used to work that you can knowledge-share here. :smile:

**Comment by adnelson** [comment]
I think we can close this guy now. Feel free to reopen if needed
