### ISSUE TITLE
Dependencies of a project with a name led by an integer is an invalid attribute name unless surrounded by double quotes

### ISSUE THREAD

**Issue by ixmatus** [adnelson/nixfromnpm#85]
I recently encountered this for a package that depends on the `7zip` npm package. Surrounding the Nix attribute name in quotes solved the evaluation errors, e.g.

```nix
"7zip-bin" = callPackage ./7zip-bin/2.2.3.nix {};
```

An easy fix would probably be to surround all of the attributes with double quotes. Though this also means the use-sites where the 7zip package is given as a build input must also be changed to select the attribute from the set with double-quote syntax.

**Comment by adnelson** [comment]
I encountered this and [fixed it](https://github.com/adnelson/nixfromnpm/commit/5c9c548e5a5ab10a1e6428379af5f28ef4e8ffcd) a little while ago; are you sure it's still broken on master?

**Comment by ixmatus** [comment]
Oh, yes, I'm definitely on an old version.
