### ISSUE TITLE
Use trick from node2nix to filter out 'Ignoring unknown extended header keyword' noise'

### ISSUE THREAD

**Issue by ixmatus** [adnelson/nixfromnpm#86]
Specifically, it's this custom tar wrapper:

```nix
  # Create a tar wrapper that filters all the 'Ignoring unknown extended header keyword' noise
  tarWrapper = runCommand "tarWrapper" {} ''
    mkdir -p $out/bin
    cat > $out/bin/tar <<EOF
    #! ${stdenv.shell} -e
    $(type -p tar) "\$@" --warning=no-unknown-keyword
    EOF
    chmod +x $out/bin/tar
  '';
```

... that can be used to hush these types of log messages:

```
tar: Ignoring unknown extended header keyword 'NODETAR.blocks'
tar: Ignoring unknown extended header keyword 'NODETAR.atimeMs'
tar: Ignoring unknown extended header keyword 'NODETAR.mtimeMs'
```

**Comment by adnelson** [comment]
hah that's awesome. happy to use that; I hate all those error messages. Want to PR?

**Comment by ixmatus** [comment]
Yeah sure, I was building `wire-desktop` with nixfromnpm and encountered them and had the thought but won't be able to get to a PR till this weekend, so if you have free time for it, go for it :) I just wanted to capture the thought while it occurred to me.

**Comment by adnelson** [comment]
do you have an example of where that gets used? does it just become a `buildInput` or what

**Comment by ixmatus** [comment]
I have a PR coming that implements this.
